Title:  50 000 Finnish Numbers
Subtitle:  And 5 000 Each of Roman and English
Author:  hugovk
Date:   4 November 2014
ShortTitle:  50kFiNo
Tags: generated, pi, Finnish, English, Roman, numbers, numerals, Roman numerals
CSS:  ../css/Manuscript_WASS.css


