Title:  Red Star Falling
Subtitle:  Agents Temporal #1 
Author:  Ian Hocking
Date:   June 6, 2013
Revision:  342385
ShortTitle:  RSF
Series:  The Agents Temporal Series
SeriesIndex:  1
Tags: science fiction
Cover: images/red_star_falling_cover.jpg
CSS:  css/Manuscript_WASS.css


