##Table of Contents

[Chapter 1: 10 000 Finnish Numbers][]

[Chapter 2: 10 000 Finnish Numbers by Length of Word][]

[Chapter 3: 10 000 Finnish Numbers in Alphabetical Order][]

[Chapter 4: 5 000 Roman Numerals and 5 000 Finnish Numbers][]

[Chapter 5: 10 000 Alternating Finnish and English Numbers][]

[Chapter 6: 10 000 Digits of Pi in Finnish][]

